spring.jpa.show-sql=false

logging.level.root=WARN
logging.level.cabalgatas_salento.reservas=INFO

spring.flyway.baseline-on-migrate=false

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
